Blogge.Web/Controllers/BlogPostController.cs
using Blogge.Web.Data;
using Blogge.Web.Models.Domain;
using Blogge.Web.Models.ViewModel;
using Blogge.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Runtime.InteropServices;
namespace Blogge.Web.Controllers
{
    public class BlogPostController : Controller
    {
        private readonly ITagRepositories tagRepositories;

        public IBlogPostRepositories BlogPostRepositories { get; }

        public BlogPostController(ITagRepositories tagRepositories,IBlogPostRepositories blogPostRepositories)
        {
            this.tagRepositories = tagRepositories;
            BlogPostRepositories = blogPostRepositories;
        }
        [Authorize( Roles ="Admin")]
        [HttpGet]
        public async Task< IActionResult >Add()
        {
            var taglist =  await tagRepositories.GetAllAsync();

            var tags = new AddBlogPostRequest
            {
                ListItems = taglist.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
            };
            return View(tags);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult >Add(AddBlogPostRequest addBlogPost)
        {
            var post = new BlogPost
            {
                Heading = addBlogPost.Heading,
                PageTitle = addBlogPost.PageTitle,
                Content = addBlogPost.Content,
                ShortDescription = addBlogPost.ShortDescription,
                FeaturedImageUrl = addBlogPost.FeaturedImageUrl,
                UrlHandle = addBlogPost.UrlHandle,
                PublishedDate = addBlogPost.PublishedDate,
                Author=addBlogPost.Author,
                Visible = addBlogPost.Visible,
                          
                 

            };

            //Map ListItem to selectedTag
            var selectedTag = new List<Tag>();
            foreach(var SeletedTagId in addBlogPost.SelectedTags)
            {
                var SelectedTagIdAsGuid = Guid.Parse(SeletedTagId);
           var exitingTag=     await tagRepositories.GetAsync(SelectedTagIdAsGuid);
                selectedTag.Add(exitingTag);

            }
            //This is ADD TO Tags of BlogPost 
            post.Tags=selectedTag;
             await BlogPostRepositories.AddAsyanc(post);
            return RedirectToAction("Add");


        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> List()
        {
           var existingPost=  await BlogPostRepositories.GetAllAsync();
            //var posts=bloggieDbContext.Posts.ToList();
            return View(existingPost);
        }
        //Map ListItem to selectedTag
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var post = await BlogPostRepositories.GetAsyanc(id);
            var tagDomainModel = await tagRepositories.GetAllAsync();
            if (post != null) {
                var blogPost = new EditBlogPostRequest
                {
                    Id = post.Id,
                    Heading = post.Heading,
                    PageTitle = post.PageTitle,
                    Content = post.Content,
                    ShortDescription = post.ShortDescription,
                    FeaturedImageUrl = post.FeaturedImageUrl,
                    UrlHandle = post.UrlHandle,
                    PublishedDate = post.PublishedDate,
                    Author = post.Author,
                    Visible = post.Visible,
                    ListItems=tagDomainModel.Select( x=>new SelectListItem
                    {
                        Text=x.Name,
                        Value=x.Id.ToString()
                    }),
                   SelectedTags= post.Tags.Select(x =>x.Id.ToString()).ToArray(),

                   
        };
      
                return View(blogPost);

            }
            else
            {
                return RedirectToAction("Edit");
            }

           
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ActionName("Edit")]
        public async Task<ActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {

            var post = new BlogPost
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                PageTitle = editBlogPostRequest.PageTitle,
                Content = editBlogPostRequest.Content,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,
                UrlHandle = editBlogPostRequest.UrlHandle,
                PublishedDate = editBlogPostRequest.PublishedDate,
                Author = editBlogPostRequest.Author,
                Visible = editBlogPostRequest.Visible,


            };
            var seletedTag = new List<Tag>();
            foreach (var selectedTag in editBlogPostRequest.SelectedTags)
            {
                if (Guid.TryParse(selectedTag, out var Tag))
                {
                    var foundTag = await tagRepositories.GetAsync(Tag);
                    if (foundTag != null)
                    {
                        seletedTag.Add(foundTag);
                    }
                }
            }
            post.Tags = seletedTag;
            var updated = await BlogPostRepositories.UpdateAsyanc(post);
            if (updated != null)
            {
                return RedirectToAction("List");

            }
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
   public async Task<IActionResult>Delete(EditBlogPostRequest editBlogPostRequest)
        { 
            var deleted= await BlogPostRepositories.DeleteAsyanc(editBlogPostRequest.Id);
            if(deleted != null)
            {
                return RedirectToAction("List");
            }
            else
            { 
                return RedirectToAction("Edit");
            }
            
        }
            
        }
    }

Blogge.Web/Controllers/TagController.cs
using Blogge.Web.Data;
using Blogge.Web.Models.Domain;
using Blogge.Web.Models.ViewModel;
using Blogge.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blogge.Web.Controllers
{
    public class TagController : Controller
    {
        private readonly ITagRepositories tagRepositories;
        //private readonly BloggieDbContext bloggieDbContext;

        //public TagController(BloggieDbContext bloggieDbContext)
        //{
        //    this.bloggieDbContext = bloggieDbContext;
        //}
        public TagController(ITagRepositories tagRepositories)
        {
           this.tagRepositories = tagRepositories;
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName,
            };
            await tagRepositories.AddAsync(tag);
            return RedirectToAction("List");


       }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        [ActionName("List")]
        public  async Task<IActionResult> List()
        {
            //var list = tagRepositories.GetAllAsync();
            var tages = await tagRepositories.GetAllAsync();
            return View(tages);
        }

        //    return View(list);
        //}
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            //var tags= bloggieDbContext.Tags.FindAsync(id);
            var tags = await tagRepositories.GetAsync(id);
            if (tags != null)
            {
                var editTagRequest = new EditTagRequest

                {
                    Id=tags.Id,
                   Name= tags.Name,
                   DisplayName= tags.DisplayName,

                };
                return View(editTagRequest);
            }

            return View();
            }








        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            var tags = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName,
            };

            var update = await tagRepositories.UpdateAsync(tags);
            if (update != null)
            {
                return RedirectToAction("List");
            }
            else
            {
                return View(editTagRequest);
            }
        }

        //    return RedirectToAction("List");

        //}
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ActionName("Delete")]
            public async Task<IActionResult >Delete(EditTagRequest editTagRequest)
        {
            var tags = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName,
            };
            var deleted= await tagRepositories.DeleteAsync(tags.Id);
            if(deleted != null)
            {
                return RedirectToAction("List");
            }

            return View(editTagRequest);
        }
                

            //{
            //    return View(tag);
            //    //_dbContext.Tags.Remove(tag);
            //    //_dbContext.SaveChanges();   
            //    //return RedirectToAction("List");
            //}


    }
}

Blogge.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blogge.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Blogge.Web.styles.css" asp-append-version="true" />
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow ">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Blog Bazar</a>
                <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(signInManager.IsSignedIn(User) &&User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin Tag
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Tag" asp-action="Add">Add Tag</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Tag" asp-action="List">Show All Tags</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="BlogPost" asp-action="Add">Add Admin BlogPost Tag</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="BlogPost" asp-action="List">Show All Admin BlogPost </a></li>
                                </ul>
                            </li>
                        }
                        
                    </ul>
                    <div class="d-flex align-items-center">
                        @if(signInManager.IsSignedIn(User))
                        {
                            <div class="me-3 text-light">
                                @User?.Identity?.Name
                                </div>
                                 <a class="btn me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>

                        }
                        else
                        {
                            <a class="btn me-3 bg-light text-success rounded-pill" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            <a class="btn me-3 bg-light text-warning rounded-pill" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        }
                       

                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Blogge.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>